name: otp_auth
description: A Dart package for generating and verifying HOTP and TOTP one-time passwords using RFC 4226 and RFC 6238.
version: 1.0.1
homepage: https://gabrimatic.info
repository: https://github.com/gabrimatic/otp_auth
issue_tracker: https://github.com/gabrimatic/otp_auth/issues
topics:
  - otp
  - totp
  - hotp
  - authenticator
  - two-factor-auth
funding:
  - https://www.buymeacoffee.com/gabrimatic

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.7

dev_dependencies:
  lints: ^5.1.0
  test: ^1.24.0
